version: '3'
volumes:
    dados:
networks: 
    banco:
    web:
    fila:            
services:
    db:
        image: postgres:9.6.9
        volumes:
            #volume de dados
            - dados:/var/lib/postgresql/data
            #scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5432:5432
        networks: 
            - banco 
    frontend:
        image: nginx:1.13
        volumes:
            - ./web:/usr/share/nginx/html/
           #configuração do proxy reverson
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks: 
            - web
            # faz o orquestramento
        depends_on: 
            - app            
    app:
        image: python:3.6
        volumes:
                #dentro do container python existe uma pasta chamada app
            - ./app:/app
            #esse /app que esta sendo referencia é o app do container
        working_dir: /app
        command: bash ./app.sh
        networks: 
            - banco
            - web
            - fila              
        depends_on: 
            - db
            - queue
    queue:
        image: redis:3.2
        networks: 
            - fila
    worker:
        # image: python:3.6
        build: worker
        volumes: 
            - ./worker:/worker
        working_dir: /worker
        # command: ./app.sh
        command: worker.py
        networks: 
            - fila
        depends_on: 
            - queue                

